# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmdb-netflix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tmdb-netflix

  target 'tmdb-netflixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tmdb-netflixUITests' do
    # Pods for testing
  end

end
